### ISSUE TITLE
Build fails with latest legacy v8

### ISSUE THREAD

**Issue by outpaddling** [jeroen/V8#90]
Thanks to changes in the underlying v8 API, the R v8 package no longer compiles with the legacy v8 engine.
I did some digging and found that some functions like SetPointerInInternalField() were deprecated in 3.15 and removed in 3.16.  I'm trying to build with 3.18 with the results shown below.
Cheers,
    Jason

```
trying URL 'https://cran.mtu.edu/src/contrib/V8_3.1.0.tar.gz'
Content type 'application/x-gzip' length 680306 bytes (664 KB)
==================================================
downloaded 664 KB

* installing *source* package ���V8��� ...
** package ���V8��� successfully unpacked and MD5 sums checked
** using staged installation
Using PKG_CFLAGS=-I/usr/include/v8 -I/usr/include/v8-3.14
Using PKG_LIBS=-lv8 -lv8_libplatform
Found legacy version of libv8
** libs
rm -f V8.so legacy/V8.o legacy/v8_typed_array.o legacy/RcppExports.o
c++ -std=gnu++11 -I"/usr/local/lib/R/include" -DNDEBUG -I/usr/include/v8 -I/usr/include/v8-3.14 -Ilegacy -I'/sharedapps/R/Rcpp/include' -DLIBICONV_PLUG -I/usr/local/include -isystem /usr/local/include  -DV8_DISABLE_DEPRECATIONS -fvisibility=hidden -fpic  -O2 -pipe -DLIBICONV_PLUG -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing  -DLIBICONV_PLUG -isystem /usr/local/include   -c legacy/V8.cpp -o legacy/V8.o
c++ -std=gnu++11 -I"/usr/local/lib/R/include" -DNDEBUG -I/usr/include/v8 -I/usr/include/v8-3.14 -Ilegacy -I'/sharedapps/R/Rcpp/include' -DLIBICONV_PLUG -I/usr/local/include -isystem /usr/local/include  -DV8_DISABLE_DEPRECATIONS -fvisibility=hidden -fpic  -O2 -pipe -DLIBICONV_PLUG -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing  -DLIBICONV_PLUG -isystem /usr/local/include   -c legacy/v8_typed_array.cpp -o legacy/v8_typed_array.o
legacy/v8_typed_array.cpp:105:18: error: no member named
      'SetPointerInInternalField' in 'v8::Object'; did you mean
      'SetAlignedPointerInInternalField'?
    args.This()->SetPointerInInternalField(0, buf);
                 ^~~~~~~~~~~~~~~~~~~~~~~~~
                 SetAlignedPointerInInternalField
/usr/local/include/v8.h:1874:8: note: 'SetAlignedPointerInInternalField'
      declared here
  void SetAlignedPointerInInternalField(int index, void* value);
       ^
legacy/v8_typed_array.cpp:218:27: error: no member named
      'GetPointerFromInternalField' in 'v8::Object'
      void* buf = buffer->GetPointerFromInternalField(0);
                  ~~~~~~  ^
legacy/v8_typed_array.cpp:231:27: error: no member named
      'GetPointerFromInternalField' in 'v8::Object'
      void* buf = buffer->GetPointerFromInternalField(0);
                  ~~~~~~  ^
legacy/v8_typed_array.cpp:258:27: error: no member named
      'GetPointerFromInternalField' in 'v8::Object'
      void* buf = buffer->GetPointerFromInternalField(0);
                  ~~~~~~  ^
4 errors generated.
gmake: *** [/usr/local/lib/R/etc/Makeconf:174: legacy/v8_typed_array.o] Error 1
ERROR: compilation failed for package ���V8���

```

**Comment by jeroen** [comment]
Which os/distro are you on?

**Comment by outpaddling** [comment]
FreeBSD, but this is a v8 engine API issue, not an OS issue.  Anyone using legacy v8 >= 3.16 is going to hit this, I think.

[https://chromium.googlesource.com/v8/v8/+/3.16.5%5E!/
](https://chromium.googlesource.com/v8/v8/+/3.16.5%5E!/
)
Maybe not many people still using the legacy v8 branch, but if you're still supporting it, you should probably support the latest release.

Cheers,

   Jason

**Comment by jeroen** [comment]
The problem is that libv8 changes the api every month so it is impossible to write bindings that will work for any version. The current R package ships two implementations: one that works for libv8 <= 3.15 and one that works for libv8 6 and up. This covers all major distributions.

There isn't much I can do to make it work with v8 version 3.18. I'm not a FreeBSD user but I would highly recommend trying to update libv8 to a more modern version. On Debian and Fedora we are using a shared libv8 LTS from nodejs these days, that works really well.

**Comment by jeroen** [comment]
This is pretty much a guess, but can you check if the `legacy318` branch works for you?

```r
remotes::install_github("jeroen/V8@legacy318")
```

**Comment by outpaddling** [comment]
What I did for now is resurrect the 3.15 version of the FreeBSD port:
[https://github.com/outpaddling/freebsd-ports-wip/tree/master/v8](https://github.com/outpaddling/freebsd-ports-wip/tree/master/v8)
That's just a stop-gap, though.
There doesn't seem to be a lot of interest in maintaining the V8 FreeBSD port, maybe due to the unstable API you mentioned among other things.
I'm actually a little perplexed as to why V8 is required for the bioinformatics package I'm working with, DiffBind.  I plan to talk to the DiffBind developers about eliminating unnecessary and troublesome deps before doing anything else.
The legacy318 branch does build and install, so thanks for that suggestion.
Is there a reason you need to stay with the 3.15 API for the CRAN package?  I would think the last release of the legacy branch would usually be a better choice, as it might have important security and bug fixes.
Thanks,
    Jason

**Comment by ateucher** [comment]
Just to put in my 2c. In https://github.com/ateucher/rmapshaper, the js library needs libv8 >= 6 for much of its functionality because it needs ES6 support. I assume this is becoming more and more common, and I would be happy if `V8` dropped the legacy v8 support.
